### PR TITLE
ft #156005300: Integrate fastlane

### PR DESCRIPTION
**Pull request by King-Benx**
#### What does this PR do?
This PR integrates fastlane into our android application

#### Description of Task to be completed?
Initially, there was no integration of tools such as slack to be able to monitor our project.
This PR delivers fastlane integration that enables us send notifications to slack.

#### SCREENSHOTS
screen shot 2018-08-28 at 12 52 53

#### How should this be manually tested?
1. Clone the repository onto your local machine
2. Set the following environment variables in your terminal
```
	export LC_ALL=en_US.UTF-8
	export LANG=en_US.UTF-8
```

3. Open android-level-up workspace on slack.
4. Run `fastlane test` in your terminal
5. Run `fastlane mock` in your terminal to upload apk to slack
6. Check converge-codelab-qa

#### Background context
NONE

#### What are the relevant pivotal tracker stories?
[Delivers #156005300]

### CODE REVIEW

**Comment by TheDancerCodes** [comment]
@King-Benx 
Great job on this integration. 👏 
I can't seem to see the `apk` being deployed to the slack channel.

**Comment by King-Benx** [comment]
Apks can be delivered as well

**Comment by Jak-Sidious** [comment]
Simillar to what was said above. Just tried to deploy to the channel and I don't see it deployed

**Comment by King-Benx** [comment]
when you run fastlane mock it should deploy the apk

**Comment by Jak-Sidious** [comment]
LGTM

**Pull request merged**
